// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA--zAmQ2vzDePt8HfO68mwZBFqAM4rxmw',
    appId: '1:899698375945:web:e9a9513fe5aa0c66a527d8',
    messagingSenderId: '899698375945',
    projectId: 'fb-auth-flutter-bloc',
    authDomain: 'fb-auth-flutter-bloc.firebaseapp.com',
    storageBucket: 'fb-auth-flutter-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl_rtnWLCKMEggoK6hIxEiynDqh4Sg_n4',
    appId: '1:899698375945:android:6995941485dd94d4a527d8',
    messagingSenderId: '899698375945',
    projectId: 'fb-auth-flutter-bloc',
    storageBucket: 'fb-auth-flutter-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6GdTDQc6Kycv9kNhO8X0Of7QZLDXRS8M',
    appId: '1:899698375945:ios:6b9a5f9f0c9685baa527d8',
    messagingSenderId: '899698375945',
    projectId: 'fb-auth-flutter-bloc',
    storageBucket: 'fb-auth-flutter-bloc.appspot.com',
    iosClientId: '899698375945-cv97fufe1sffo9loviqog97uhha41e05.apps.googleusercontent.com',
    iosBundleId: 'com.hieubui.life',
  );
}
